version: '3.8'
services:
    backend:
        build: ./backend
        ports:
            - '8000:8000'
        env_file:
            - ./backend/.production.env
        depends_on:
            - postgres
        command: /bin/sh -c "npm run seed:prod && npm run start:prod"

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '111418'
            POSTGRES_DB: delivery
        volumes:
            - postgres_data:/var/lib/postgresql/data

    frontend:
        build: ./frontend
        ports:
            - '8080:8080'
        env_file:
            - ./frontend/.env
        stdin_open: true
        tty: true
        depends_on:
            - backend

volumes:
    postgres_data:
