version: '3.8'
services:
    backend:
        build: ./backend
        ports:
            - '8000:8000'
        env_file:
            - ./backend/.env
    frontend:
        build: ./frontend
        ports:
            - '8080:8080'
        env_file:
            - ./frontend/.env
        stdin_open: true
        tty: true
        depends_on:
            - backend
